### ISSUE TITLE
Node 4.x?

### ISSUE THREAD

**Issue by vielmetti** [hypriot/rpi-node#2]
Note that there's now a Node.JS 4.0.0 out, with ARM binaries in the official distribution

https://nodejs.org/en/download/

This has separate ARM6, ARM7, and ARM8 releases, and I don't know if it's possible to do a Dockerfile that intelligently switches among them, or if you'd need an 'rpi-node' and 'rpi2-node' setup.

Also note that the whole Node.JS ecosystem is busy patching and porting to get modules to work, as they changed the `nan` component, and dozens of `npm` modules that depend on that need non-trivial work to get that to go.

**Comment by StefanScherer** [comment]
@vielmetti thanks for the reminder! Yes, your're right, after a [Windows Dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/master/node/4.0/Dockerfile) and a Chocolatey package it is time for ARM as well :smile: 

Switching the cpu type might work with different tags. What about this?
- 4.0.0, 4.0, latest (4.0/Dockerfile)
- 4.0.0-onbuild, 4.0-onbuild, onbuild (4.0/onbuild/Dockerfile)
- 4.0.0-slim, 4.0-slim, slim (4.0/slim/Dockerfile)
- 4.0.0-wheezy, 4.0-wheezy, wheezy (4.0/wheezy/Dockerfile)
- 4.0.0-armv7, 4.0-armv7 (4.0-armv7/Dockerfile)
- 4.0.0-armv7-onbuild, 4.0-armv7-onbuild (4.0-armv7/onbuild/Dockerfile)
- 4.0.0-armv7-slim, 4.0-armv7-slim (4.0-armv7/slim/Dockerfile)
- 4.0.0-armv7-wheezy, 4.0-armv7-wheezy (4.0-armv7/wheezy/Dockerfile)
- 4.0.0-armv8, 4.0-armv8 (4.0-armv8/Dockerfile)
- 4.0.0-armv8-onbuild, 4.0-armv8-onbuild (4.0-armv8/onbuild/Dockerfile)
- 4.0.0-armv8-slim, 4.0-armv8-slim (4.0-armv8/slim/Dockerfile)
- 4.0.0-armv8-wheezy, 4.0-armv8-wheezy (4.0-armv8/wheezy/Dockerfile)

OK, the number of tags are exploding, but the idea is to put only one runtime into the Docker Image.

**Comment by vielmetti** [comment]
Looks complex (but manageably so). There's more possible complexity as more releases of Node come out post-4.0 to deal with the issues that will inevitably emerge with all of the changes.

**Comment by StefanScherer** [comment]
I have started a PR #3 for that.

**Comment by StefanScherer** [comment]
Done with #3
