### ISSUE TITLE
Fails to build on windows

### ISSUE THREAD

**Issue by kokarn** [hypriot/rpi-node#23]
Hello! I'm very new to Docker, so might be my fault 100%.

I'm trying to follow along the [examples](https://docs.docker.com/engine/examples/nodejs_web_app/) with a really basic Dockerfile but I get som weird errors.

The example that uses `centos:centos6` works great but when i switch to `hypriot/rpi-node:4.4.3` it errors out. 
I've also tried `ubuntu:14.04` which works, and the Dockerfile for `hypriot/rpi-node:4.4.3` directly which errors.

Dockerfile

``` Dockerfile
FROM    hypriot/rpi-node:4.4.3

COPY    package.json package.json
RUN     ["npm", "install", "--production"]

COPY    server.js server.js

EXPOSE  8080

CMD     ["node", "server.js"]
```

Log output for my Dockerfile

``` log
Sending build context to Docker daemon 80.67 MB
Step 1 : FROM hypriot/rpi-node:4.4.3
 ---> 4f926a7e9322
Step 2 : COPY package.json package.json
 ---> Using cache
 ---> a699223f1b79
Step 3 : RUN npm install --production 
---> Running in e3ac170cf67f
rpc error: code = 2 desc = "oci runtime error: exec format error"
```

**Comment by StefanScherer** [comment]
@kokarn Welcome to Docker 🐳 

Do you want to build a Docker image for a Raspberry Pi or a similar small board?
If you just want to learn Docker and run it on your computer (eg. a Windows computer with a VirtualBox VM / Docker Toolbox installation), just use "node" instead of "hypriot/rpi-node".

**Comment by kokarn** [comment]
Thanks!

Yeah, it's a RPi 2 that i'm targeting. It's going to be a control unit for a bunch of BLE devices and I have the code running without Docker. Just interested to try to dockerify it :)

**Comment by StefanScherer** [comment]
You could use `docker-machine.exe` to connect to your RPi2 and run the `docker build ...` from your Windows PC. Otherwise log into your RPi2 and run the docker commands there.

**Comment by kokarn** [comment]
Yeah, I know how I can solve if with a VM or the Raspberry. 
I was mainly curious why this Dockerfile in particular was breaking, seems they should be pretty platform independent :)

**Comment by StefanScherer** [comment]
The "exec format error" normally means "you have the wrong CPU" :-)
There is QEMU to emulate other CPU's and some weeks ago we were surprised to see this Docker image running on Mac and Windows with the Docker for Mac/Windows Beta (which had QEMU built-in) - don't know if it makes it into the official release.

**Comment by kokarn** [comment]
Probably not, Docker on windows needs a lot more care before it's ready.

Thanks for the quick support, i'll build in a VM or directly on the RPi for now.
