### ISSUE TITLE
[6.5.0-wheezy] GLIBCXX_3.4.18 not found (required by node)

### ISSUE THREAD

**Issue by goliatone** [hypriot/rpi-node#29]
Building a Dockerfile from `hypriot/rpi-node:6.5.0-wheezy` with `hypriotos-rpi-v1.0.0`  fails with the following error:

> node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by node)

**Comment by StefanScherer** [comment]
Have you tried the hypriot/rpi-node without wheezy?
I would like to get rid of so many images, I just ported all of them to ARM and I would prefer an alpine version instead of wheezy :-)

**Comment by goliatone** [comment]
yes, non wheezy seems to work fine

**Comment by StefanScherer** [comment]
@goliatone In latest builds I have removed wheezy. You should consider using the newer images.
