### ISSUE TITLE
Release node 6.7.0

### ISSUE THREAD

**Issue by caseywebdev** [hypriot/rpi-node#30]
Security release came out yesterday, would love to get a new build! Also, thanks for maintaining this.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.7.0

**Comment by StefanScherer** [comment]
There is hypriot/rpi-node 6.9.1 on Docker Hub. I'll close this one.

**Comment by caseywebdev** [comment]
Thanks 👍🏻
