### ISSUE TITLE
Please add an alpine-version

### ISSUE THREAD

**Issue by cgHome** [hypriot/rpi-node#31]
#Please add an alpine-version  / THX...

**Comment by StefanScherer** [comment]
This repo is based on the upstream node docker image https://hub.docker.com/r/library/node/ and they also do not provide an alpine version. 

So someone should make the effort and port eg. https://hub.docker.com/r/mhart/alpine-node/ to ARM.

But as Node.js is moving so fast it is out of my scope to keep up with an alpine version as well as we're lacking behind the current Node.js versions in this repo ;-)

**Comment by cgHome** [comment]
Thank you for your quick response.

I'm looking for a rpi-alpine-node image for my smarthome server project based on hypriotOS, because the other images are relatively large and I want to work with micros-service.

(Tschüss und ein schöner Abend) Chris

PS:  Sorry musste Goggle-Translate verwenden

**Comment by ind3x** [comment]
@cgHome , I am in the same situation as you. I think that an Alpine version for node (and other images) will be a good idea and it makes sense for IoT devices.

Also, there is a trend of moving official images to Alpine (https://www.brianchristner.io/docker-is-moving-to-alpine-linux/) and hopefully there is an official image as soon as possible.

Finally, as @StefanScherer says, maybe someone should make the effort 😄

**Comment by StefanScherer** [comment]
Oh, today I recognized that there is an official Alpine Docker image with Node.js, eg. https://github.com/nodejs/docker-node/blob/57f7537d35c0988bd0e74abbf16989557c1481ad/7.3/alpine/Dockerfile

But my first step is to activate CI builds, and afterwards have a look at the Alpine Dockerfile.

**Comment by StefanScherer** [comment]
@cgHome I did a onetime local build and pushed it to Docker Hub: `hypriot/rpi-node:6.10.0-alpine`
But I guess that a Travis based build as for the other images takes too long. My MBP fan was blowing a very long time, and building that for three Node version is too much for me to maintain locally.

**Comment by azimut** [comment]
nodejs provides armv7a binaries http://nodejs.org/dist/v6.9.4/, last time I checked they were statically linked so they should work out of the box, might be with a busybox as base

**Comment by StefanScherer** [comment]
Thanks @azimut. Yes maybe in busybox. In alpine it crashed.

**Comment by azimut** [comment]
I took a look, and the binaries provided by nodejs are not statically linked. Not at least for the glibc and gcc lib dependencies. ( I need to start using readelf instead of ldd more often.)

So a minimal image would need to have glibc and gcc libs at least. I found a non-official alpine glibc based version but I haven't give it a try. For my use case I am compiling nodejs (2 hours build).

**Comment by StefanScherer** [comment]
The official images are multi-arch now and also provide an alpine version:

```
$ docker run --rm mplatform/mquery node:alpine
Image: node:alpine
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
```
