### ISSUE TITLE
Please add Yarn 

### ISSUE THREAD

**Issue by thebuccaneersden** [hypriot/rpi-node#41]
A lot of developers are switching to [Yarn](https://yarnpkg.com/en/) as a replacement to NPM (because it performs better). Even the official NodeJS docker repo has included Yarn in their builds (ie. [here](https://github.com/nodejs/docker-node/blob/master/6.10/alpine/Dockerfile)). 😄

**Comment by StefanScherer** [comment]
That is a good idea. Pull requests are welcome and would help bring this in much faster. Just fork this repo and append the steps for yarn and send a PR, Travis will run the build and we can see if it works.

**Comment by thebuccaneersden** [comment]
Awesome. I will do that. I'm currently trying to build it on my Raspberry Pi 3 and compiling NodeJS is taking forever. 😉  @StefanScherer

**Comment by thebuccaneersden** [comment]
Ok. PR created and the Travis build passed, so I guess it's up for review to be merged into your master @StefanScherer . :)

**Comment by StefanScherer** [comment]
Added in #42, thanks again.

**Comment by thebuccaneersden** [comment]
Np. It's to my own benefit really. Many thanks for providing a number of docker images sparing me the time and effort to do it myself!
