### ISSUE TITLE
Node 8 missing

### ISSUE THREAD

**Issue by bjornmagnusson** [hypriot/rpi-node#43]
Since a while ago Node 8 was released with the much improved npm5.
Could you add image with these installed?

**Comment by StefanScherer** [comment]
Good news. With PR https://github.com/nodejs/docker-node/pull/504 merged there are now semi-official Node.js Docker images at the Docker Hub: https://hub.docker.com/r/arm32v7/node/

**Comment by StefanScherer** [comment]
So please use `FROM arm32v7/node:8.4.0` instead.
Only thing is that the official images work only on Raspberry Pi 2 and 3, not the Pi Zero or old model 1.
